CREATE DATABASE MYWALLET;

DROP TABLE IF EXISTS users;
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    nombres VARCHAR(50),
    apellidos VARCHAR(50),
    telefono VARCHAR(13),
    contrasena VARCHAR(20),
    correo VARCHAR(40)
);

DROP TABLE IF EXISTS accounts;
CREATE TABLE accounts(
    id SERIAL PRIMARY  KEY,
    nombre VARCHAR(50),
    descripcion VARCHAR(50),
    idcliente INT,
    CONSTRAINT fk_user_account FOREIGN KEY (idcliente) REFERENCES users(id)
);

DROP TABLE IF EXISTS transactions;
CREATE TABLE transactions(
    id SERIAL PRIMARY KEY,
    fecha DATE,
    descripcion VARCHAR(50),
    tipo BOOLEAN,
    idcuenta INT,    
    monto INT,
    destinatario VARCHAR(50),
    CONSTRAINT fk_account FOREIGN KEY (idcuenta) REFERENCES accounts(id)    
);

INSERT INTO USERS (NOMBRES,APELLIDOS,TELEFONO,CONTRASENA,CORREO) VALUES ('Pepito','Perez','12345','asdf1234','pepito1@gmail.com');
INSERT INTO USERS (NOMBRES,APELLIDOS,TELEFONO,CONTRASENA,CORREO) VALUES ('Armando','Casas','12345','asdf1234','pepito2@gmail.com');

INSERT INTO ACCOUNTS(NOMBRE,DESCRIPCION,IDCLIENTE) VALUES ('Cuenta de Ahorros', 'Cuenta bancaria',1);
INSERT INTO ACCOUNTS(NOMBRE,DESCRIPCION,IDCLIENTE) VALUES ('Nequi', 'Plata para mecatearsela en cositas',2);
INSERT INTO ACCOUNTS(NOMBRE,DESCRIPCION,IDCLIENTE) VALUES ('Paypal', 'Transacciones internacionales',1);
INSERT INTO ACCOUNTS(NOMBRE,DESCRIPCION,IDCLIENTE) VALUES ('Paypal', 'Transacciones internacionales',2);

INSERT INTO TRANSACTIONS (FECHA,DESCRIPCION,TIPO,IDCUENTA,MONTO,DESTINATARIO)  VALUES ('2021-05-22','Mi trabajo vale',TRUE,1,2000500,'SALARIO');
INSERT INTO TRANSACTIONS (FECHA,DESCRIPCION,TIPO,IDCUENTA,MONTO,DESTINATARIO)  VALUES ('2021-05-22','Domicilio almuerzo',False,1,10000,'iFood');
INSERT INTO TRANSACTIONS (FECHA,DESCRIPCION,TIPO,IDCUENTA,MONTO,DESTINATARIO)  VALUES ('2021-05-23','Domicilio cena',False,1,13000,'iFood');
INSERT INTO TRANSACTIONS (FECHA,DESCRIPCION,TIPO,IDCUENTA,MONTO,DESTINATARIO)  VALUES ('2021-05-22','Ahorro',TRUE,2,1000500,'SALARIO');
INSERT INTO TRANSACTIONS (FECHA,DESCRIPCION,TIPO,IDCUENTA,MONTO,DESTINATARIO)  VALUES ('2021-05-22','Ahorro',TRUE,3,1000500,'SUGGAR DADDY');
INSERT INTO TRANSACTIONS (FECHA,DESCRIPCION,TIPO,IDCUENTA,MONTO,DESTINATARIO)  VALUES ('2021-05-22','Ahorro',TRUE,4,1000500,'SUGGAR MOMMY');