CREATE DATABASE MYWALLET;

CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    TELEFONO VARCHAR(13),
    CONTRASENA VARCHAR(20),
    CORREO VARCHAR(40)
);

CREATE TABLE ACCOUNTS(
    ID SERIAL PRIMARY  KEY,
    NOMBRE VARCHAR(50),
    DESCRIPCION VARCHAR(50)
    IDCLIENTE INT,
    CONSTRAINT fk_user_account FOREIGN KEY (IDCLIENTE) REFERENCES USERS(ID)
);

CREATE TABLE TRANSACTIONS(
    ID SERIAL PRIMARY KEY,
    FECHA DATE,
    DESCRIPCION VARCHAR(50),
    TIPO BOOLEAN,
    IDCUENTA INT,
    IDCLIENTE INT, 
    MONTO INT,
    DESTINATARIO VARCHAR(50),
    CONSTRAINT fk_account FOREIGN KEY (IDCUENTA) REFERENCES ACCOUNTS(ID),
    CONSTRAINT fk_user_transaction FOREIGN KEY (IDCLIENTE) REFERENCES USERS(ID)
);

INSERT INTO USERS (NOMBRES,APELLIDOS,TELEFONO,CONTRASENA,CORREO) VALUES ('Pepito','Perez','12345','asdf1234','pepito1@gmail.com');
INSERT INTO USERS (NOMBRES,APELLIDOS,TELEFONO,CONTRASENA,CORREO) VALUES ('Armando','Casas','12345','asdf1234','pepito2@gmail.com');

INSERT INTO ACCOUNTS(NOMBRE,DESCRIPCION,IDCLIENTE) VALUES ('Cuenta de Ahorros', 'Cuenta bancaria',1);
INSERT INTO ACCOUNTS(NOMBRE,DESCRIPCION,IDCLIENTE) VALUES ('Nequi', 'Plata para mecatearsela en cositas',2);


